
conveior:
  speed: 10
  width: 100
  length: 2000
  spawn_rate: 100
  
arm:
  span: 50
  speed: 10
  pick_time: 2
  drop_time: 1
  rest_dist: -10 
  drop_dist: -40
  base_pos: 50
  arm_dist: 300
  count: 3